output_prefix: ./output/test
instance_file: ./sample_instance/instance_a_2LMM.txt
fringe_tree_file: ./sample_instance/ins_a_fringe_2LMM.txt
original_dataset_filename: ./sample_instance/Hc_desc.csv

# model can be ANN or LR
input_data:
  # - model: ANN
  #   prefix: ./sample_instance/sample/At_large
  #   target_value_lower_bound: 0
  #   target_value_upper_bound: 1920
  # - model: ANN
  #   prefix: ./sample_instance/sample/At_large
  #   target_value_lower_bound: 0
  #   target_value_upper_bound: 1930
  - model: LR
    prefix: ./sample_instance/Hc
    target_value_lower_bound: 9200
    target_value_upper_bound: 10000
  - model: LR
    prefix: sample_instance/Hc
    target_value_lower_bound: 9250
    target_value_upper_bound: 10000
    