output_prefix: ./tests/output/test
instance_file: ./tests/input/instance_files/instance_a_2LMM.txt
fringe_tree_file: ./tests/input/fringe_files/ins_a_fringe_2LMM.txt
input_data:
  # - model: LR
  #   prefix: ./tests/input/data/Mp_small
  #   target_value_lower_bound: -208.79
  #   target_value_upper_bound: 40.0
  - model: RF
    prefix: ./tests/input/data/Bp_small
    target_value_lower_bound: -268.928
    target_value_upper_bound: 10000.0
  - model: ANN
    prefix: ./tests/input/data/Fp_small
    target_value_lower_bound: -188.0
    target_value_upper_bound: 63.44444444444444

